### ISSUE TITLE
Add support for gpt-3.5-turbo model

### ISSUE THREAD

**Issue by minipasila** [miku-gg/miku#5]
Considering that it's cheaper than the current text-davinci-003 model. (gpt-3.5=$0.002 per 1K tokens vs gpt-3=$0.02 per 1K tokens)

**Comment by miku448** [comment]
In progress, please check #6 
I tested it a bit but it has a bit of a restrictive filter, I'd say it's close to `davinci` in complexity or reponses, if not better. I'll upload a new bot demo with that one plugged in.

**Comment by miku448** [comment]
Merged
